### ISSUE TITLE
How to set hitsPerpage count ?

### ISSUE THREAD

**Issue by webdev1014** [algolia/demo-infinite-scroll#6]

**Comment by Haroenv** [comment]
You can do that in two spaces. The first one is on the [dashboard](https://www.algolia.com/dashboard/explorer) (display -> display & pagination -> hitsPerPage)

The second method is by doing it runtime. You can add the `hitsPerPage` in the `searchParameters` block of InstantSearch here: [search/results.js](https://github.com/algolia/demo-infinite-scroll/blob/master/src/js/search/results.js#L10)

Feel free to reopen with more information if you need it.
